LogOutModal
ElizPery/project-frontend-DarkHorsesTeam pull request #15
Opened 2024-10-18 21:16 UTC by ValeriyaHr

2024-10-18 21:17 UTC, ValeriyaHr commented
user not fond

2024-10-19 08:48 UTC, ElizPery requested changes

2024-10-19 08:48 UTC, ElizPery commented on .env.example
> +REACT_APP_API_URL=
змінних оточення тут не буде, поки що url буде зберігатись в операціях

2024-10-19 08:48 UTC, ElizPery commented on src/redux/auth/operations.js
> +const BASE_URL = import.meta.env.VITE_API_URL;
Тут буде додано 

axios.defaults.baseURL = "";

При логіні буде використана ця функція
const setAuthHeader = (token) => {
  axios.defaults.headers.common.Authorization = `Bearer ${token}`;
};

Тобто після login заголовак буде для всіх запитів

2024-10-19 08:48 UTC, ElizPery commented on src/redux/auth/operations.js
> +            Authorization: `Bearer ${localStorage.getItem('token')}`,
Тут не потрібні заголовки

2024-10-19 08:48 UTC, ElizPery commented on src/redux/auth/operations.js
> +        await axios.post(`${BASE_URL}/users/logout`, null, {
роут просто "/users/logout", baseURL буде вже буде додано до всіх запитів

2024-10-19 08:48 UTC, ElizPery commented on src/redux/auth/operations.js
> +        localStorage.removeItem('token');
необхідно ще дописати та розкоментити функцію, щоб почистити дефолтні заголовки axios

clearAuthHeader();

2024-10-19 08:48 UTC, ElizPery commented on src/redux/auth/slice.js
> +              .addCase(logoutUser.rejected, (state, action) => {
Якщо відмовлено то також чистимо стан, для безпеки

2024-10-19 08:48 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +import { useTranslation } from 'react-i18next';
react-i18next немає в залежностях, треба тоді додати, через це я не можу подивитись зовнішній вигляд модалки, видає відразу помилки

2024-10-19 14:23 UTC, ElizPery requested changes

2024-10-19 14:23 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +          {t('logout.buttonCancel')}
Немає ще іконки крестика для закриття

2024-10-19 14:23 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +  return (
Також необхфдно додати бєкдроп та при написканні на нього або escapeмодалка закривається

2024-10-19 14:23 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +        <h3>{t('logout.title')}</h3>
Ці назви не відображаються коректно

2024-10-19 14:23 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +          onClick={handleLogout}
До стилей додати тінь кнопки

2024-10-19 14:23 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +          onClick={handleCloseModal}
Колір тексту білий, повинен бути синій

2024-10-19 14:23 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.module.css
> +    }
Окрім цих налаштувань змінюється розташування кнопок, будь ласка переглянь ще раз макет та застосовані стилі

https://www.figma.com/design/QlavVIeBoi8Bpc8ystMApI/WaterTracker-with-backend?node-id=0-1&node-type=canvas&t=t5FDPDx1TRpzhTgb-0

2024-10-19 14:23 UTC, ElizPery commented on src/redux/auth/operations.js
> +      await axios.post("/users/logout");
В минулий раз не помітила, запит на logout відбувається на "/auth/logout"

2024-10-20 18:29 UTC, ElizPery requested changes

2024-10-20 18:29 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +          <h3>{t('Log out')}</h3>
По макету інші відступи у версії mobile

2024-10-20 18:29 UTC, ElizPery commented on src/components/UserLogoutModal/UserLogoutModal.jsx
> +  };
закриття модалки не працює ні в якому вигляді

2024-10-21 07:53 UTC, merged